[package]
name = "rustynes"
version = "0.1.0"
edition = "2021"

# [features]
# nestest = []

[dependencies]
raylib = "5.0.1"
rand = "0.8.5"
bitfield-struct = "0.7.0"

[dev-dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
lazy_static = "1.4.0"
